/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisorSimpleRouteImport } from './routes/visor-simple'
import { Route as SondaRouteImport } from './routes/sonda'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Qa3dRouteImport } from './routes/qa3d'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as Mbar24RouteImport } from './routes/mbar24'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as GithubStatusRouteImport } from './routes/github-status'
import { Route as FsleExportRouteImport } from './routes/fsle-export'
import { Route as FrentesRouteImport } from './routes/frentes'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTileProxyRouteImport } from './routes/api.tile-proxy'
import { Route as ApiMbar24IndexRouteImport } from './routes/api.mbar24-index'
import { Route as ApiMbar24DownloadRouteImport } from './routes/api.mbar24-download'
import { Route as ApiDemRouteImport } from './routes/api.dem'
import { Route as ApiBathymetryRouteImport } from './routes/api.bathymetry'
import { Route as ApiPublicGpxDownloadRouteImport } from './routes/api.public.gpx-download'
import { Route as ApiPublicFsleGeojsonDownloadRouteImport } from './routes/api.public.fsle-geojson-download'
import { Route as ApiPublicFsleRouteImport } from './routes/api.public.fsle'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api.public.payments.webhook'

const VisorSimpleRoute = VisorSimpleRouteImport.update({
  id: '/visor-simple',
  path: '/visor-simple',
  getParentRoute: () => rootRouteImport,
} as any)
const SondaRoute = SondaRouteImport.update({
  id: '/sonda',
  path: '/sonda',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Qa3dRoute = Qa3dRouteImport.update({
  id: '/qa3d',
  path: '/qa3d',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const Mbar24Route = Mbar24RouteImport.update({
  id: '/mbar24',
  path: '/mbar24',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubStatusRoute = GithubStatusRouteImport.update({
  id: '/github-status',
  path: '/github-status',
  getParentRoute: () => rootRouteImport,
} as any)
const FsleExportRoute = FsleExportRouteImport.update({
  id: '/fsle-export',
  path: '/fsle-export',
  getParentRoute: () => rootRouteImport,
} as any)
const FrentesRoute = FrentesRouteImport.update({
  id: '/frentes',
  path: '/frentes',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTileProxyRoute = ApiTileProxyRouteImport.update({
  id: '/api/tile-proxy',
  path: '/api/tile-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMbar24IndexRoute = ApiMbar24IndexRouteImport.update({
  id: '/api/mbar24-index',
  path: '/api/mbar24-index',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMbar24DownloadRoute = ApiMbar24DownloadRouteImport.update({
  id: '/api/mbar24-download',
  path: '/api/mbar24-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemRoute = ApiDemRouteImport.update({
  id: '/api/dem',
  path: '/api/dem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBathymetryRoute = ApiBathymetryRouteImport.update({
  id: '/api/bathymetry',
  path: '/api/bathymetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGpxDownloadRoute = ApiPublicGpxDownloadRouteImport.update({
  id: '/api/public/gpx-download',
  path: '/api/public/gpx-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFsleGeojsonDownloadRoute =
  ApiPublicFsleGeojsonDownloadRouteImport.update({
    id: '/api/public/fsle-geojson-download',
    path: '/api/public/fsle-geojson-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFsleRoute = ApiPublicFsleRouteImport.update({
  id: '/api/public/fsle',
  path: '/api/public/fsle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cuenta': typeof CuentaRoute
  '/frentes': typeof FrentesRoute
  '/fsle-export': typeof FsleExportRoute
  '/github-status': typeof GithubStatusRoute
  '/guia': typeof GuiaRoute
  '/mbar24': typeof Mbar24Route
  '/precios': typeof PreciosRoute
  '/privacy': typeof PrivacyRoute
  '/qa3d': typeof Qa3dRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sonda': typeof SondaRoute
  '/visor-simple': typeof VisorSimpleRoute
  '/api/bathymetry': typeof ApiBathymetryRoute
  '/api/dem': typeof ApiDemRoute
  '/api/mbar24-download': typeof ApiMbar24DownloadRoute
  '/api/mbar24-index': typeof ApiMbar24IndexRoute
  '/api/tile-proxy': typeof ApiTileProxyRoute
  '/api/public/fsle': typeof ApiPublicFsleRoute
  '/api/public/fsle-geojson-download': typeof ApiPublicFsleGeojsonDownloadRoute
  '/api/public/gpx-download': typeof ApiPublicGpxDownloadRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cuenta': typeof CuentaRoute
  '/frentes': typeof FrentesRoute
  '/fsle-export': typeof FsleExportRoute
  '/github-status': typeof GithubStatusRoute
  '/guia': typeof GuiaRoute
  '/mbar24': typeof Mbar24Route
  '/precios': typeof PreciosRoute
  '/privacy': typeof PrivacyRoute
  '/qa3d': typeof Qa3dRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sonda': typeof SondaRoute
  '/visor-simple': typeof VisorSimpleRoute
  '/api/bathymetry': typeof ApiBathymetryRoute
  '/api/dem': typeof ApiDemRoute
  '/api/mbar24-download': typeof ApiMbar24DownloadRoute
  '/api/mbar24-index': typeof ApiMbar24IndexRoute
  '/api/tile-proxy': typeof ApiTileProxyRoute
  '/api/public/fsle': typeof ApiPublicFsleRoute
  '/api/public/fsle-geojson-download': typeof ApiPublicFsleGeojsonDownloadRoute
  '/api/public/gpx-download': typeof ApiPublicGpxDownloadRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cuenta': typeof CuentaRoute
  '/frentes': typeof FrentesRoute
  '/fsle-export': typeof FsleExportRoute
  '/github-status': typeof GithubStatusRoute
  '/guia': typeof GuiaRoute
  '/mbar24': typeof Mbar24Route
  '/precios': typeof PreciosRoute
  '/privacy': typeof PrivacyRoute
  '/qa3d': typeof Qa3dRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sonda': typeof SondaRoute
  '/visor-simple': typeof VisorSimpleRoute
  '/api/bathymetry': typeof ApiBathymetryRoute
  '/api/dem': typeof ApiDemRoute
  '/api/mbar24-download': typeof ApiMbar24DownloadRoute
  '/api/mbar24-index': typeof ApiMbar24IndexRoute
  '/api/tile-proxy': typeof ApiTileProxyRoute
  '/api/public/fsle': typeof ApiPublicFsleRoute
  '/api/public/fsle-geojson-download': typeof ApiPublicFsleGeojsonDownloadRoute
  '/api/public/gpx-download': typeof ApiPublicGpxDownloadRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cuenta'
    | '/frentes'
    | '/fsle-export'
    | '/github-status'
    | '/guia'
    | '/mbar24'
    | '/precios'
    | '/privacy'
    | '/qa3d'
    | '/reset-password'
    | '/sonda'
    | '/visor-simple'
    | '/api/bathymetry'
    | '/api/dem'
    | '/api/mbar24-download'
    | '/api/mbar24-index'
    | '/api/tile-proxy'
    | '/api/public/fsle'
    | '/api/public/fsle-geojson-download'
    | '/api/public/gpx-download'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cuenta'
    | '/frentes'
    | '/fsle-export'
    | '/github-status'
    | '/guia'
    | '/mbar24'
    | '/precios'
    | '/privacy'
    | '/qa3d'
    | '/reset-password'
    | '/sonda'
    | '/visor-simple'
    | '/api/bathymetry'
    | '/api/dem'
    | '/api/mbar24-download'
    | '/api/mbar24-index'
    | '/api/tile-proxy'
    | '/api/public/fsle'
    | '/api/public/fsle-geojson-download'
    | '/api/public/gpx-download'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cuenta'
    | '/frentes'
    | '/fsle-export'
    | '/github-status'
    | '/guia'
    | '/mbar24'
    | '/precios'
    | '/privacy'
    | '/qa3d'
    | '/reset-password'
    | '/sonda'
    | '/visor-simple'
    | '/api/bathymetry'
    | '/api/dem'
    | '/api/mbar24-download'
    | '/api/mbar24-index'
    | '/api/tile-proxy'
    | '/api/public/fsle'
    | '/api/public/fsle-geojson-download'
    | '/api/public/gpx-download'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CuentaRoute: typeof CuentaRoute
  FrentesRoute: typeof FrentesRoute
  FsleExportRoute: typeof FsleExportRoute
  GithubStatusRoute: typeof GithubStatusRoute
  GuiaRoute: typeof GuiaRoute
  Mbar24Route: typeof Mbar24Route
  PreciosRoute: typeof PreciosRoute
  PrivacyRoute: typeof PrivacyRoute
  Qa3dRoute: typeof Qa3dRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SondaRoute: typeof SondaRoute
  VisorSimpleRoute: typeof VisorSimpleRoute
  ApiBathymetryRoute: typeof ApiBathymetryRoute
  ApiDemRoute: typeof ApiDemRoute
  ApiMbar24DownloadRoute: typeof ApiMbar24DownloadRoute
  ApiMbar24IndexRoute: typeof ApiMbar24IndexRoute
  ApiTileProxyRoute: typeof ApiTileProxyRoute
  ApiPublicFsleRoute: typeof ApiPublicFsleRoute
  ApiPublicFsleGeojsonDownloadRoute: typeof ApiPublicFsleGeojsonDownloadRoute
  ApiPublicGpxDownloadRoute: typeof ApiPublicGpxDownloadRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visor-simple': {
      id: '/visor-simple'
      path: '/visor-simple'
      fullPath: '/visor-simple'
      preLoaderRoute: typeof VisorSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sonda': {
      id: '/sonda'
      path: '/sonda'
      fullPath: '/sonda'
      preLoaderRoute: typeof SondaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa3d': {
      id: '/qa3d'
      path: '/qa3d'
      fullPath: '/qa3d'
      preLoaderRoute: typeof Qa3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mbar24': {
      id: '/mbar24'
      path: '/mbar24'
      fullPath: '/mbar24'
      preLoaderRoute: typeof Mbar24RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-status': {
      id: '/github-status'
      path: '/github-status'
      fullPath: '/github-status'
      preLoaderRoute: typeof GithubStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fsle-export': {
      id: '/fsle-export'
      path: '/fsle-export'
      fullPath: '/fsle-export'
      preLoaderRoute: typeof FsleExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frentes': {
      id: '/frentes'
      path: '/frentes'
      fullPath: '/frentes'
      preLoaderRoute: typeof FrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tile-proxy': {
      id: '/api/tile-proxy'
      path: '/api/tile-proxy'
      fullPath: '/api/tile-proxy'
      preLoaderRoute: typeof ApiTileProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mbar24-index': {
      id: '/api/mbar24-index'
      path: '/api/mbar24-index'
      fullPath: '/api/mbar24-index'
      preLoaderRoute: typeof ApiMbar24IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mbar24-download': {
      id: '/api/mbar24-download'
      path: '/api/mbar24-download'
      fullPath: '/api/mbar24-download'
      preLoaderRoute: typeof ApiMbar24DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dem': {
      id: '/api/dem'
      path: '/api/dem'
      fullPath: '/api/dem'
      preLoaderRoute: typeof ApiDemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bathymetry': {
      id: '/api/bathymetry'
      path: '/api/bathymetry'
      fullPath: '/api/bathymetry'
      preLoaderRoute: typeof ApiBathymetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gpx-download': {
      id: '/api/public/gpx-download'
      path: '/api/public/gpx-download'
      fullPath: '/api/public/gpx-download'
      preLoaderRoute: typeof ApiPublicGpxDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fsle-geojson-download': {
      id: '/api/public/fsle-geojson-download'
      path: '/api/public/fsle-geojson-download'
      fullPath: '/api/public/fsle-geojson-download'
      preLoaderRoute: typeof ApiPublicFsleGeojsonDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fsle': {
      id: '/api/public/fsle'
      path: '/api/public/fsle'
      fullPath: '/api/public/fsle'
      preLoaderRoute: typeof ApiPublicFsleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CuentaRoute: CuentaRoute,
  FrentesRoute: FrentesRoute,
  FsleExportRoute: FsleExportRoute,
  GithubStatusRoute: GithubStatusRoute,
  GuiaRoute: GuiaRoute,
  Mbar24Route: Mbar24Route,
  PreciosRoute: PreciosRoute,
  PrivacyRoute: PrivacyRoute,
  Qa3dRoute: Qa3dRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SondaRoute: SondaRoute,
  VisorSimpleRoute: VisorSimpleRoute,
  ApiBathymetryRoute: ApiBathymetryRoute,
  ApiDemRoute: ApiDemRoute,
  ApiMbar24DownloadRoute: ApiMbar24DownloadRoute,
  ApiMbar24IndexRoute: ApiMbar24IndexRoute,
  ApiTileProxyRoute: ApiTileProxyRoute,
  ApiPublicFsleRoute: ApiPublicFsleRoute,
  ApiPublicFsleGeojsonDownloadRoute: ApiPublicFsleGeojsonDownloadRoute,
  ApiPublicGpxDownloadRoute: ApiPublicGpxDownloadRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
